package com.jh.land.entity;

import com.jh.util.CacheUtil;
import com.jh.util.cache.IdTransform;

import java.math.BigDecimal;
import java.util.Date;

public class DsAreaRank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_area_rank.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_area_rank.region_id
     *
     * @mbggenerated
     */
    private Long regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_area_rank.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_area_rank.data_status
     *
     * @mbggenerated
     */
    private String dataStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_area_rank.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_area_rank.creator_name
     *
     * @mbggenerated
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_area_rank.creator
     *
     * @mbggenerated
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_area_rank.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_area_rank.modifier_name
     *
     * @mbggenerated
     */
    private String modifierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_area_rank.modifier
     *
     * @mbggenerated
     */
    private Integer modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_area_rank.crop_id
     *
     * @mbggenerated
     */
    private Integer cropId;

    @IdTransform(type= CacheUtil.CACHE_DICT_TYPE,propName = "cropId")
    private String cropName;//作物中文名

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_area_rank.area
     *
     * @mbggenerated
     */
    private BigDecimal area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_area_rank.year
     *
     * @mbggenerated
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_area_rank.data_type
     *
     * @mbggenerated
     */
    private Integer dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_area_rank.publish_status
     *
     * @mbggenerated
     */
    private Integer publishStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_area_rank.publish_time
     *
     * @mbggenerated
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_area_rank.publisher_name
     *
     * @mbggenerated
     */
    private String publisherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_area_rank.data_time
     *
     * @mbggenerated
     */
    private Date dataTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_area_rank.del_flag
     *
     * @mbggenerated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_area_rank.publisher
     *
     * @mbggenerated
     */
    private Integer publisher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_area_rank.resolution
     *
     * @mbggenerated
     */
    private Integer resolution;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_area_rank.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_area_rank.id
     *
     * @return the value of ds_area_rank.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_area_rank.id
     *
     * @param id the value for ds_area_rank.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_area_rank.region_id
     *
     * @return the value of ds_area_rank.region_id
     *
     * @mbggenerated
     */
    public Long getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_area_rank.region_id
     *
     * @param regionId the value for ds_area_rank.region_id
     *
     * @mbggenerated
     */
    public void setRegionId(Long regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_area_rank.remark
     *
     * @return the value of ds_area_rank.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_area_rank.remark
     *
     * @param remark the value for ds_area_rank.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_area_rank.data_status
     *
     * @return the value of ds_area_rank.data_status
     *
     * @mbggenerated
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_area_rank.data_status
     *
     * @param dataStatus the value for ds_area_rank.data_status
     *
     * @mbggenerated
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus == null ? null : dataStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_area_rank.create_time
     *
     * @return the value of ds_area_rank.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_area_rank.create_time
     *
     * @param createTime the value for ds_area_rank.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_area_rank.creator_name
     *
     * @return the value of ds_area_rank.creator_name
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_area_rank.creator_name
     *
     * @param creatorName the value for ds_area_rank.creator_name
     *
     * @mbggenerated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_area_rank.creator
     *
     * @return the value of ds_area_rank.creator
     *
     * @mbggenerated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_area_rank.creator
     *
     * @param creator the value for ds_area_rank.creator
     *
     * @mbggenerated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_area_rank.modify_time
     *
     * @return the value of ds_area_rank.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_area_rank.modify_time
     *
     * @param modifyTime the value for ds_area_rank.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_area_rank.modifier_name
     *
     * @return the value of ds_area_rank.modifier_name
     *
     * @mbggenerated
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_area_rank.modifier_name
     *
     * @param modifierName the value for ds_area_rank.modifier_name
     *
     * @mbggenerated
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName == null ? null : modifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_area_rank.modifier
     *
     * @return the value of ds_area_rank.modifier
     *
     * @mbggenerated
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_area_rank.modifier
     *
     * @param modifier the value for ds_area_rank.modifier
     *
     * @mbggenerated
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_area_rank.crop_id
     *
     * @return the value of ds_area_rank.crop_id
     *
     * @mbggenerated
     */
    public Integer getCropId() {
        return cropId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_area_rank.crop_id
     *
     * @param cropId the value for ds_area_rank.crop_id
     *
     * @mbggenerated
     */
    public void setCropId(Integer cropId) {
        this.cropId = cropId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_area_rank.area
     *
     * @return the value of ds_area_rank.area
     *
     * @mbggenerated
     */
    public BigDecimal getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_area_rank.area
     *
     * @param area the value for ds_area_rank.area
     *
     * @mbggenerated
     */
    public void setArea(BigDecimal area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_area_rank.year
     *
     * @return the value of ds_area_rank.year
     *
     * @mbggenerated
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_area_rank.year
     *
     * @param year the value for ds_area_rank.year
     *
     * @mbggenerated
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_area_rank.data_type
     *
     * @return the value of ds_area_rank.data_type
     *
     * @mbggenerated
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_area_rank.data_type
     *
     * @param dataType the value for ds_area_rank.data_type
     *
     * @mbggenerated
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_area_rank.publish_status
     *
     * @return the value of ds_area_rank.publish_status
     *
     * @mbggenerated
     */
    public Integer getPublishStatus() {
        return publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_area_rank.publish_status
     *
     * @param publishStatus the value for ds_area_rank.publish_status
     *
     * @mbggenerated
     */
    public void setPublishStatus(Integer publishStatus) {
        this.publishStatus = publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_area_rank.publish_time
     *
     * @return the value of ds_area_rank.publish_time
     *
     * @mbggenerated
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_area_rank.publish_time
     *
     * @param publishTime the value for ds_area_rank.publish_time
     *
     * @mbggenerated
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_area_rank.publisher_name
     *
     * @return the value of ds_area_rank.publisher_name
     *
     * @mbggenerated
     */
    public String getPublisherName() {
        return publisherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_area_rank.publisher_name
     *
     * @param publisherName the value for ds_area_rank.publisher_name
     *
     * @mbggenerated
     */
    public void setPublisherName(String publisherName) {
        this.publisherName = publisherName == null ? null : publisherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_area_rank.data_time
     *
     * @return the value of ds_area_rank.data_time
     *
     * @mbggenerated
     */
    public Date getDataTime() {
        return dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_area_rank.data_time
     *
     * @param dataTime the value for ds_area_rank.data_time
     *
     * @mbggenerated
     */
    public void setDataTime(Date dataTime) {
        this.dataTime = dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_area_rank.del_flag
     *
     * @return the value of ds_area_rank.del_flag
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_area_rank.del_flag
     *
     * @param delFlag the value for ds_area_rank.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_area_rank.publisher
     *
     * @return the value of ds_area_rank.publisher
     *
     * @mbggenerated
     */
    public Integer getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_area_rank.publisher
     *
     * @param publisher the value for ds_area_rank.publisher
     *
     * @mbggenerated
     */
    public void setPublisher(Integer publisher) {
        this.publisher = publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_area_rank.resolution
     *
     * @return the value of ds_area_rank.resolution
     *
     * @mbggenerated
     */
    public Integer getResolution() {
        return resolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_area_rank.resolution
     *
     * @param resolution the value for ds_area_rank.resolution
     *
     * @mbggenerated
     */
    public void setResolution(Integer resolution) {
        this.resolution = resolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_area_rank.product_id
     *
     * @return the value of ds_area_rank.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_area_rank.product_id
     *
     * @param productId the value for ds_area_rank.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public String getCropName() {
        return cropName;
    }

    public void setCropName(String cropName) {
        this.cropName = cropName;
    }
}