package com.jh.land.entity;

import java.time.LocalDateTime;
import java.util.Date;

public class DsRankTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_rank_task.task_id
     *
     * @mbggenerated
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_rank_task.data_status
     *
     * @mbggenerated
     */
    private String dataStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_rank_task.del_flag
     *
     * @mbggenerated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_rank_task.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_rank_task.creator_name
     *
     * @mbggenerated
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_rank_task.creator
     *
     * @mbggenerated
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_rank_task.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_rank_task.modifier_name
     *
     * @mbggenerated
     */
    private String modifierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_rank_task.modifier
     *
     * @mbggenerated
     */
    private Integer modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_rank_task.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_rank_task.publish_status
     *
     * @mbggenerated
     */
    private Integer publishStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_rank_task.publish_time
     *
     * @mbggenerated
     */
    private LocalDateTime publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_rank_task.publisher_name
     *
     * @mbggenerated
     */
    private String publisherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_rank_task.publisher
     *
     * @mbggenerated
     */
    private Integer publisher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_rank_task.task_name
     *
     * @mbggenerated
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_rank_task.crop_id
     *
     * @mbggenerated
     */
    private Integer cropId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_rank_task.storage_url
     *
     * @mbggenerated
     */
    private String storageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_rank_task.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_rank_task.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_rank_task.fail_reason
     *
     * @mbggenerated
     */
    private String failReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_rank_task.task_status
     *
     * @mbggenerated
     */
    private Integer taskStatus;

    private Long regionId;

    private String regionCode;


    private Date dataTime;

    private Integer productType;

    private Integer level;

    //分布/长势/估产数据所属地块数据图层
    private Date shpTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_rank_task.task_id
     *
     * @return the value of ds_rank_task.task_id
     *
     * @mbggenerated
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_rank_task.task_id
     *
     * @param taskId the value for ds_rank_task.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_rank_task.data_status
     *
     * @return the value of ds_rank_task.data_status
     *
     * @mbggenerated
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_rank_task.data_status
     *
     * @param dataStatus the value for ds_rank_task.data_status
     *
     * @mbggenerated
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus == null ? null : dataStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_rank_task.del_flag
     *
     * @return the value of ds_rank_task.del_flag
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_rank_task.del_flag
     *
     * @param delFlag the value for ds_rank_task.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_rank_task.create_time
     *
     * @return the value of ds_rank_task.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_rank_task.create_time
     *
     * @param createTime the value for ds_rank_task.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_rank_task.creator_name
     *
     * @return the value of ds_rank_task.creator_name
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_rank_task.creator_name
     *
     * @param creatorName the value for ds_rank_task.creator_name
     *
     * @mbggenerated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_rank_task.creator
     *
     * @return the value of ds_rank_task.creator
     *
     * @mbggenerated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_rank_task.creator
     *
     * @param creator the value for ds_rank_task.creator
     *
     * @mbggenerated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_rank_task.modify_time
     *
     * @return the value of ds_rank_task.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_rank_task.modify_time
     *
     * @param modifyTime the value for ds_rank_task.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_rank_task.modifier_name
     *
     * @return the value of ds_rank_task.modifier_name
     *
     * @mbggenerated
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_rank_task.modifier_name
     *
     * @param modifierName the value for ds_rank_task.modifier_name
     *
     * @mbggenerated
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName == null ? null : modifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_rank_task.modifier
     *
     * @return the value of ds_rank_task.modifier
     *
     * @mbggenerated
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_rank_task.modifier
     *
     * @param modifier the value for ds_rank_task.modifier
     *
     * @mbggenerated
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_rank_task.remark
     *
     * @return the value of ds_rank_task.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_rank_task.remark
     *
     * @param remark the value for ds_rank_task.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_rank_task.publish_status
     *
     * @return the value of ds_rank_task.publish_status
     *
     * @mbggenerated
     */
    public Integer getPublishStatus() {
        return publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_rank_task.publish_status
     *
     * @param publishStatus the value for ds_rank_task.publish_status
     *
     * @mbggenerated
     */
    public void setPublishStatus(Integer publishStatus) {
        this.publishStatus = publishStatus;
    }

    public LocalDateTime getPublishTime() {
        return publishTime;
    }

    public void setPublishTime(LocalDateTime publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_rank_task.publisher_name
     *
     * @return the value of ds_rank_task.publisher_name
     *
     * @mbggenerated
     */
    public String getPublisherName() {
        return publisherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_rank_task.publisher_name
     *
     * @param publisherName the value for ds_rank_task.publisher_name
     *
     * @mbggenerated
     */
    public void setPublisherName(String publisherName) {
        this.publisherName = publisherName == null ? null : publisherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_rank_task.publisher
     *
     * @return the value of ds_rank_task.publisher
     *
     * @mbggenerated
     */
    public Integer getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_rank_task.publisher
     *
     * @param publisher the value for ds_rank_task.publisher
     *
     * @mbggenerated
     */
    public void setPublisher(Integer publisher) {
        this.publisher = publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_rank_task.task_name
     *
     * @return the value of ds_rank_task.task_name
     *
     * @mbggenerated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_rank_task.task_name
     *
     * @param taskName the value for ds_rank_task.task_name
     *
     * @mbggenerated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_rank_task.crop_id
     *
     * @return the value of ds_rank_task.crop_id
     *
     * @mbggenerated
     */
    public Integer getCropId() {
        return cropId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_rank_task.crop_id
     *
     * @param cropId the value for ds_rank_task.crop_id
     *
     * @mbggenerated
     */
    public void setCropId(Integer cropId) {
        this.cropId = cropId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_rank_task.storage_url
     *
     * @return the value of ds_rank_task.storage_url
     *
     * @mbggenerated
     */
    public String getStorageUrl() {
        return storageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_rank_task.storage_url
     *
     * @param storageUrl the value for ds_rank_task.storage_url
     *
     * @mbggenerated
     */
    public void setStorageUrl(String storageUrl) {
        this.storageUrl = storageUrl == null ? null : storageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_rank_task.start_time
     *
     * @return the value of ds_rank_task.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_rank_task.start_time
     *
     * @param startTime the value for ds_rank_task.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_rank_task.end_time
     *
     * @return the value of ds_rank_task.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_rank_task.end_time
     *
     * @param endTime the value for ds_rank_task.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_rank_task.fail_reason
     *
     * @return the value of ds_rank_task.fail_reason
     *
     * @mbggenerated
     */
    public String getFailReason() {
        return failReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_rank_task.fail_reason
     *
     * @param failReason the value for ds_rank_task.fail_reason
     *
     * @mbggenerated
     */
    public void setFailReason(String failReason) {
        this.failReason = failReason == null ? null : failReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_rank_task.task_status
     *
     * @return the value of ds_rank_task.task_status
     *
     * @mbggenerated
     */
    public Integer getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_rank_task.task_status
     *
     * @param taskStatus the value for ds_rank_task.task_status
     *
     * @mbggenerated
     */
    public void setTaskStatus(Integer taskStatus) {
        this.taskStatus = taskStatus;
    }



    public Integer getProductType() {
        return productType;
    }

    public void setProductType(Integer productType) {
        this.productType = productType;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }


    public Long getRegionId() {
        return regionId;
    }

    public void setRegionId(Long regionId) {
        this.regionId = regionId;
    }

    public String getRegionCode() {
        return regionCode;
    }

    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode;
    }

    public Date getDataTime() {
        return dataTime;
    }

    public void setDataTime(Date dataTime) {
        this.dataTime = dataTime;
    }

    public Date getShpTime() {
        return shpTime;
    }

    public void setShpTime(Date shpTime) {
        this.shpTime = shpTime;
    }
}