package com.jh.land.entity;

public class InitSoilTypeName {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column init_soil_type_name.first_type_name
     *
     * @mbggenerated
     */
    private String firstTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column init_soil_type_name.first_type_id
     *
     * @mbggenerated
     */
    private String firstTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column init_soil_type_name.second_type_name
     *
     * @mbggenerated
     */
    private String secondTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column init_soil_type_name.second_type_id
     *
     * @mbggenerated
     */
    private String secondTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column init_soil_type_name.third_type_name
     *
     * @mbggenerated
     */
    private String thirdTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column init_soil_type_name.third_type_id
     *
     * @mbggenerated
     */
    private String thirdTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column init_soil_type_name.soil_type
     *
     * @mbggenerated
     */
    private String soilType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column init_soil_type_name.first_type_name
     *
     * @return the value of init_soil_type_name.first_type_name
     *
     * @mbggenerated
     */
    public String getFirstTypeName() {
        return firstTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column init_soil_type_name.first_type_name
     *
     * @param firstTypeName the value for init_soil_type_name.first_type_name
     *
     * @mbggenerated
     */
    public void setFirstTypeName(String firstTypeName) {
        this.firstTypeName = firstTypeName == null ? null : firstTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column init_soil_type_name.first_type_id
     *
     * @return the value of init_soil_type_name.first_type_id
     *
     * @mbggenerated
     */
    public String getFirstTypeId() {
        return firstTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column init_soil_type_name.first_type_id
     *
     * @param firstTypeId the value for init_soil_type_name.first_type_id
     *
     * @mbggenerated
     */
    public void setFirstTypeId(String firstTypeId) {
        this.firstTypeId = firstTypeId == null ? null : firstTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column init_soil_type_name.second_type_name
     *
     * @return the value of init_soil_type_name.second_type_name
     *
     * @mbggenerated
     */
    public String getSecondTypeName() {
        return secondTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column init_soil_type_name.second_type_name
     *
     * @param secondTypeName the value for init_soil_type_name.second_type_name
     *
     * @mbggenerated
     */
    public void setSecondTypeName(String secondTypeName) {
        this.secondTypeName = secondTypeName == null ? null : secondTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column init_soil_type_name.second_type_id
     *
     * @return the value of init_soil_type_name.second_type_id
     *
     * @mbggenerated
     */
    public String getSecondTypeId() {
        return secondTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column init_soil_type_name.second_type_id
     *
     * @param secondTypeId the value for init_soil_type_name.second_type_id
     *
     * @mbggenerated
     */
    public void setSecondTypeId(String secondTypeId) {
        this.secondTypeId = secondTypeId == null ? null : secondTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column init_soil_type_name.third_type_name
     *
     * @return the value of init_soil_type_name.third_type_name
     *
     * @mbggenerated
     */
    public String getThirdTypeName() {
        return thirdTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column init_soil_type_name.third_type_name
     *
     * @param thirdTypeName the value for init_soil_type_name.third_type_name
     *
     * @mbggenerated
     */
    public void setThirdTypeName(String thirdTypeName) {
        this.thirdTypeName = thirdTypeName == null ? null : thirdTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column init_soil_type_name.third_type_id
     *
     * @return the value of init_soil_type_name.third_type_id
     *
     * @mbggenerated
     */
    public String getThirdTypeId() {
        return thirdTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column init_soil_type_name.third_type_id
     *
     * @param thirdTypeId the value for init_soil_type_name.third_type_id
     *
     * @mbggenerated
     */
    public void setThirdTypeId(String thirdTypeId) {
        this.thirdTypeId = thirdTypeId == null ? null : thirdTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column init_soil_type_name.soil_type
     *
     * @return the value of init_soil_type_name.soil_type
     *
     * @mbggenerated
     */
    public String getSoilType() {
        return soilType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column init_soil_type_name.soil_type
     *
     * @param soilType the value for init_soil_type_name.soil_type
     *
     * @mbggenerated
     */
    public void setSoilType(String soilType) {
        this.soilType = soilType == null ? null : soilType.trim();
    }
}