 package com.jh.land.entity;

import java.math.BigDecimal;
import java.util.Date;

 public class InitRank {
     /**
      * This field was generated by MyBatis Generator.
      * This field corresponds to the database column init_rank.rank_id
      *
      * @mbggenerated
      */
     private Long rankId;

     /**
      * This field was generated by MyBatis Generator.
      * This field corresponds to the database column init_rank.data_status
      *
      * @mbggenerated
      */
     private String dataStatus;

     /**
      * This field was generated by MyBatis Generator.
      * This field corresponds to the database column init_rank.del_flag
      *
      * @mbggenerated
      */
     private String delFlag;

     /**
      * This field was generated by MyBatis Generator.
      * This field corresponds to the database column init_rank.create_time
      *
      * @mbggenerated
      */
     private Date createTime;

     /**
      * This field was generated by MyBatis Generator.
      * This field corresponds to the database column init_rank.creator_name
      *
      * @mbggenerated
      */
     private String creatorName;

     /**
      * This field was generated by MyBatis Generator.
      * This field corresponds to the database column init_rank.creator
      *
      * @mbggenerated
      */
     private Integer creator;

     /**
      * This field was generated by MyBatis Generator.
      * This field corresponds to the database column init_rank.modify_time
      *
      * @mbggenerated
      */
     private Date modifyTime;

     /**
      * This field was generated by MyBatis Generator.
      * This field corresponds to the database column init_rank.modifier_name
      *
      * @mbggenerated
      */
     private String modifierName;

     /**
      * This field was generated by MyBatis Generator.
      * This field corresponds to the database column init_rank.modifier
      *
      * @mbggenerated
      */
     private Integer modifier;

     /**
      * This field was generated by MyBatis Generator.
      * This field corresponds to the database column init_rank.remark
      *
      * @mbggenerated
      */
     private String remark;

     /**
      * This field was generated by MyBatis Generator.
      * This field corresponds to the database column init_rank.rank_code
      *
      * @mbggenerated
      */
     private String rankCode;

     /**
      * This field was generated by MyBatis Generator.
      * This field corresponds to the database column init_rank.rank_name
      *
      * @mbggenerated
      */
     private String rankName;

     /**
      * This field was generated by MyBatis Generator.
      * This field corresponds to the database column init_rank.china_name
      *
      * @mbggenerated
      */
     private String chinaName;

     /**
      * This field was generated by MyBatis Generator.
      * This field corresponds to the database column init_rank.level
      *
      * @mbggenerated
      */
     private Integer level;

     /**
      * This field was generated by MyBatis Generator.
      * This field corresponds to the database column init_rank.parent_id
      *
      * @mbggenerated
      */
     private Long parentId;

     /**
      * This field was generated by MyBatis Generator.
      * This field corresponds to the database column init_rank.area
      *
      * @mbggenerated
      */
     private BigDecimal area;

     /**
      * This field was generated by MyBatis Generator.
      * This field corresponds to the database column init_rank.lon
      *
      * @mbggenerated
      */
     private BigDecimal lon;

     /**
      * This field was generated by MyBatis Generator.
      * This field corresponds to the database column init_rank.lat
      *
      * @mbggenerated
      */
     private BigDecimal lat;

     /**
      * This field was generated by MyBatis Generator.
      * This field corresponds to the database column init_rank.bbox
      *
      * @mbggenerated
      */
     private Object bbox;

     /**
      * This field was generated by MyBatis Generator.
      * This field corresponds to the database column init_rank.vertex_bbox
      *
      * @mbggenerated
      */
     private Object vertexBbox;

     /**
      * This field was generated by MyBatis Generator.
      * This field corresponds to the database column init_rank.strip_number
      *
      * @mbggenerated
      */
     private String stripNumber;

     /**
      * This field was generated by MyBatis Generator.
      * This field corresponds to the database column init_rank.centroid
      *
      * @mbggenerated
      */
     private Object centroid;

     /**
      * This field was generated by MyBatis Generator.
      * This field corresponds to the database column init_rank.crop_id
      *
      * @mbggenerated
      */
    /* private Integer cropId;*/

     /**
      * This method was generated by MyBatis Generator.
      * This method returns the value of the database column init_rank.rank_id
      *
      * @return the value of init_rank.rank_id
      *
      * @mbggenerated
      */
     public Long getRankId() {
         return rankId;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method sets the value of the database column init_rank.rank_id
      *
      * @param rankId the value for init_rank.rank_id
      *
      * @mbggenerated
      */
     public void setRankId(Long rankId) {
         this.rankId = rankId;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method returns the value of the database column init_rank.data_status
      *
      * @return the value of init_rank.data_status
      *
      * @mbggenerated
      */
     public String getDataStatus() {
         return dataStatus;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method sets the value of the database column init_rank.data_status
      *
      * @param dataStatus the value for init_rank.data_status
      *
      * @mbggenerated
      */
     public void setDataStatus(String dataStatus) {
         this.dataStatus = dataStatus == null ? null : dataStatus.trim();
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method returns the value of the database column init_rank.del_flag
      *
      * @return the value of init_rank.del_flag
      *
      * @mbggenerated
      */
     public String getDelFlag() {
         return delFlag;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method sets the value of the database column init_rank.del_flag
      *
      * @param delFlag the value for init_rank.del_flag
      *
      * @mbggenerated
      */
     public void setDelFlag(String delFlag) {
         this.delFlag = delFlag == null ? null : delFlag.trim();
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method returns the value of the database column init_rank.create_time
      *
      * @return the value of init_rank.create_time
      *
      * @mbggenerated
      */
     public Date getCreateTime() {
         return createTime;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method sets the value of the database column init_rank.create_time
      *
      * @param createTime the value for init_rank.create_time
      *
      * @mbggenerated
      */
     public void setCreateTime(Date createTime) {
         this.createTime = createTime;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method returns the value of the database column init_rank.creator_name
      *
      * @return the value of init_rank.creator_name
      *
      * @mbggenerated
      */
     public String getCreatorName() {
         return creatorName;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method sets the value of the database column init_rank.creator_name
      *
      * @param creatorName the value for init_rank.creator_name
      *
      * @mbggenerated
      */
     public void setCreatorName(String creatorName) {
         this.creatorName = creatorName == null ? null : creatorName.trim();
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method returns the value of the database column init_rank.creator
      *
      * @return the value of init_rank.creator
      *
      * @mbggenerated
      */
     public Integer getCreator() {
         return creator;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method sets the value of the database column init_rank.creator
      *
      * @param creator the value for init_rank.creator
      *
      * @mbggenerated
      */
     public void setCreator(Integer creator) {
         this.creator = creator;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method returns the value of the database column init_rank.modify_time
      *
      * @return the value of init_rank.modify_time
      *
      * @mbggenerated
      */
     public Date getModifyTime() {
         return modifyTime;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method sets the value of the database column init_rank.modify_time
      *
      * @param modifyTime the value for init_rank.modify_time
      *
      * @mbggenerated
      */
     public void setModifyTime(Date modifyTime) {
         this.modifyTime = modifyTime;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method returns the value of the database column init_rank.modifier_name
      *
      * @return the value of init_rank.modifier_name
      *
      * @mbggenerated
      */
     public String getModifierName() {
         return modifierName;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method sets the value of the database column init_rank.modifier_name
      *
      * @param modifierName the value for init_rank.modifier_name
      *
      * @mbggenerated
      */
     public void setModifierName(String modifierName) {
         this.modifierName = modifierName == null ? null : modifierName.trim();
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method returns the value of the database column init_rank.modifier
      *
      * @return the value of init_rank.modifier
      *
      * @mbggenerated
      */
     public Integer getModifier() {
         return modifier;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method sets the value of the database column init_rank.modifier
      *
      * @param modifier the value for init_rank.modifier
      *
      * @mbggenerated
      */
     public void setModifier(Integer modifier) {
         this.modifier = modifier;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method returns the value of the database column init_rank.remark
      *
      * @return the value of init_rank.remark
      *
      * @mbggenerated
      */
     public String getRemark() {
         return remark;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method sets the value of the database column init_rank.remark
      *
      * @param remark the value for init_rank.remark
      *
      * @mbggenerated
      */
     public void setRemark(String remark) {
         this.remark = remark == null ? null : remark.trim();
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method returns the value of the database column init_rank.rank_code
      *
      * @return the value of init_rank.rank_code
      *
      * @mbggenerated
      */
     public String getRankCode() {
         return rankCode;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method sets the value of the database column init_rank.rank_code
      *
      * @param rankCode the value for init_rank.rank_code
      *
      * @mbggenerated
      */
     public void setRankCode(String rankCode) {
         this.rankCode = rankCode == null ? null : rankCode.trim();
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method returns the value of the database column init_rank.rank_name
      *
      * @return the value of init_rank.rank_name
      *
      * @mbggenerated
      */
     public String getRankName() {
         return rankName;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method sets the value of the database column init_rank.rank_name
      *
      * @param rankName the value for init_rank.rank_name
      *
      * @mbggenerated
      */
     public void setRankName(String rankName) {
         this.rankName = rankName == null ? null : rankName.trim();
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method returns the value of the database column init_rank.china_name
      *
      * @return the value of init_rank.china_name
      *
      * @mbggenerated
      */
     public String getChinaName() {
         return chinaName;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method sets the value of the database column init_rank.china_name
      *
      * @param chinaName the value for init_rank.china_name
      *
      * @mbggenerated
      */
     public void setChinaName(String chinaName) {
         this.chinaName = chinaName == null ? null : chinaName.trim();
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method returns the value of the database column init_rank.level
      *
      * @return the value of init_rank.level
      *
      * @mbggenerated
      */
     public Integer getLevel() {
         return level;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method sets the value of the database column init_rank.level
      *
      * @param level the value for init_rank.level
      *
      * @mbggenerated
      */
     public void setLevel(Integer level) {
         this.level = level;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method returns the value of the database column init_rank.parent_id
      *
      * @return the value of init_rank.parent_id
      *
      * @mbggenerated
      */
     public Long getParentId() {
         return parentId;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method sets the value of the database column init_rank.parent_id
      *
      * @param parentId the value for init_rank.parent_id
      *
      * @mbggenerated
      */
     public void setParentId(Long parentId) {
         this.parentId = parentId;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method returns the value of the database column init_rank.area
      *
      * @return the value of init_rank.area
      *
      * @mbggenerated
      */
     public BigDecimal getArea() {
         return area;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method sets the value of the database column init_rank.area
      *
      * @param area the value for init_rank.area
      *
      * @mbggenerated
      */
     public void setArea(BigDecimal area) {
         this.area = area;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method returns the value of the database column init_rank.lon
      *
      * @return the value of init_rank.lon
      *
      * @mbggenerated
      */
     public BigDecimal getLon() {
         return lon;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method sets the value of the database column init_rank.lon
      *
      * @param lon the value for init_rank.lon
      *
      * @mbggenerated
      */
     public void setLon(BigDecimal lon) {
         this.lon = lon;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method returns the value of the database column init_rank.lat
      *
      * @return the value of init_rank.lat
      *
      * @mbggenerated
      */
     public BigDecimal getLat() {
         return lat;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method sets the value of the database column init_rank.lat
      *
      * @param lat the value for init_rank.lat
      *
      * @mbggenerated
      */
     public void setLat(BigDecimal lat) {
         this.lat = lat;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method returns the value of the database column init_rank.bbox
      *
      * @return the value of init_rank.bbox
      *
      * @mbggenerated
      */
     public Object getBbox() {
         return bbox;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method sets the value of the database column init_rank.bbox
      *
      * @param bbox the value for init_rank.bbox
      *
      * @mbggenerated
      */
     public void setBbox(Object bbox) {
         this.bbox = bbox;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method returns the value of the database column init_rank.vertex_bbox
      *
      * @return the value of init_rank.vertex_bbox
      *
      * @mbggenerated
      */
     public Object getVertexBbox() {
         return vertexBbox;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method sets the value of the database column init_rank.vertex_bbox
      *
      * @param vertexBbox the value for init_rank.vertex_bbox
      *
      * @mbggenerated
      */
     public void setVertexBbox(Object vertexBbox) {
         this.vertexBbox = vertexBbox;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method returns the value of the database column init_rank.strip_number
      *
      * @return the value of init_rank.strip_number
      *
      * @mbggenerated
      */
     public String getStripNumber() {
         return stripNumber;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method sets the value of the database column init_rank.strip_number
      *
      * @param stripNumber the value for init_rank.strip_number
      *
      * @mbggenerated
      */
     public void setStripNumber(String stripNumber) {
         this.stripNumber = stripNumber == null ? null : stripNumber.trim();
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method returns the value of the database column init_rank.centroid
      *
      * @return the value of init_rank.centroid
      *
      * @mbggenerated
      */
     public Object getCentroid() {
         return centroid;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method sets the value of the database column init_rank.centroid
      *
      * @param centroid the value for init_rank.centroid
      *
      * @mbggenerated
      */
     public void setCentroid(Object centroid) {
         this.centroid = centroid;
     }

     /**
      * This method was generated by MyBatis Generator.
      * This method returns the value of the database column init_rank.crop_id
      *
      * @return the value of init_rank.crop_id
      *
      * @mbggenerated
      */
 /*    public Integer getCropId() {
         return cropId;
     }

     *//**
      * This method was generated by MyBatis Generator.
      * This method sets the value of the database column init_rank.crop_id
      *
      * @param cropId the value for init_rank.crop_id
      *
      * @mbggenerated
      *//*
     public void setCropId(Integer cropId) {
         this.cropId = cropId;
     }*/
 }