package com.jh.land.entity;

public class InitSoilType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column init_soil_type.region_code
     *
     * @mbggenerated
     */
    private String regionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column init_soil_type.zone_code
     *
     * @mbggenerated
     */
    private String zoneCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column init_soil_type.count
     *
     * @mbggenerated
     */
    private String count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column init_soil_type.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column init_soil_type.soil_type
     *
     * @mbggenerated
     */
    private String soilType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column init_soil_type.region_code
     *
     * @return the value of init_soil_type.region_code
     *
     * @mbggenerated
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column init_soil_type.region_code
     *
     * @param regionCode the value for init_soil_type.region_code
     *
     * @mbggenerated
     */
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode == null ? null : regionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column init_soil_type.zone_code
     *
     * @return the value of init_soil_type.zone_code
     *
     * @mbggenerated
     */
    public String getZoneCode() {
        return zoneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column init_soil_type.zone_code
     *
     * @param zoneCode the value for init_soil_type.zone_code
     *
     * @mbggenerated
     */
    public void setZoneCode(String zoneCode) {
        this.zoneCode = zoneCode == null ? null : zoneCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column init_soil_type.count
     *
     * @return the value of init_soil_type.count
     *
     * @mbggenerated
     */
    public String getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column init_soil_type.count
     *
     * @param count the value for init_soil_type.count
     *
     * @mbggenerated
     */
    public void setCount(String count) {
        this.count = count == null ? null : count.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column init_soil_type.area
     *
     * @return the value of init_soil_type.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column init_soil_type.area
     *
     * @param area the value for init_soil_type.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column init_soil_type.soil_type
     *
     * @return the value of init_soil_type.soil_type
     *
     * @mbggenerated
     */
    public String getSoilType() {
        return soilType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column init_soil_type.soil_type
     *
     * @param soilType the value for init_soil_type.soil_type
     *
     * @mbggenerated
     */
    public void setSoilType(String soilType) {
        this.soilType = soilType == null ? null : soilType.trim();
    }
}