package com.jh.land.entity;

import java.util.Date;

public class RankAreaTimes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank_area_times.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank_area_times.data_time
     *
     * @mbggenerated
     */
    private Date dataTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank_area_times.region_id
     *
     * @mbggenerated
     */
    private Long regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank_area_times.crop_id
     *
     * @mbggenerated
     */
    private Integer cropId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank_area_times.resolution
     *
     * @mbggenerated
     */
    private Integer resolution;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank_area_times.id
     *
     * @return the value of rank_area_times.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank_area_times.id
     *
     * @param id the value for rank_area_times.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank_area_times.data_time
     *
     * @return the value of rank_area_times.data_time
     *
     * @mbggenerated
     */
    public Date getDataTime() {
        return dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank_area_times.data_time
     *
     * @param dataTime the value for rank_area_times.data_time
     *
     * @mbggenerated
     */
    public void setDataTime(Date dataTime) {
        this.dataTime = dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank_area_times.region_id
     *
     * @return the value of rank_area_times.region_id
     *
     * @mbggenerated
     */
    public Long getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank_area_times.region_id
     *
     * @param regionId the value for rank_area_times.region_id
     *
     * @mbggenerated
     */
    public void setRegionId(Long regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank_area_times.crop_id
     *
     * @return the value of rank_area_times.crop_id
     *
     * @mbggenerated
     */
    public Integer getCropId() {
        return cropId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank_area_times.crop_id
     *
     * @param cropId the value for rank_area_times.crop_id
     *
     * @mbggenerated
     */
    public void setCropId(Integer cropId) {
        this.cropId = cropId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank_area_times.resolution
     *
     * @return the value of rank_area_times.resolution
     *
     * @mbggenerated
     */
    public Integer getResolution() {
        return resolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank_area_times.resolution
     *
     * @param resolution the value for rank_area_times.resolution
     *
     * @mbggenerated
     */
    public void setResolution(Integer resolution) {
        this.resolution = resolution;
    }
}