package com.jh.land.entity;

import java.math.BigDecimal;
import java.util.Date;

public class RankStatistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank_statistics.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank_statistics.parent_id
     *
     * @mbggenerated
     */
    private Long regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank_statistics.rank_num
     *
     * @mbggenerated
     */
    private Integer rankNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank_statistics.area_sum
     *
     * @mbggenerated
     */
    private BigDecimal areaSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank_statistics.data_time
     *
     * @mbggenerated
     */
    private Date dataTime;

    //区域编码
    private String regionCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank_statistics.id
     *
     * @return the value of rank_statistics.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank_statistics.id
     *
     * @param id the value for rank_statistics.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank_statistics.parent_id
     *
     * @return the value of rank_statistics.parent_id
     *
     * @mbggenerated
     */
    public Long getRegionId() {
        return regionId;
    }

    public void setRegionId(Long regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank_statistics.rank_num
     *
     * @return the value of rank_statistics.rank_num
     *
     * @mbggenerated
     */
    public Integer getRankNum() {
        return rankNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank_statistics.rank_num
     *
     * @param rankNum the value for rank_statistics.rank_num
     *
     * @mbggenerated
     */
    public void setRankNum(Integer rankNum) {
        this.rankNum = rankNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank_statistics.area_sum
     *
     * @return the value of rank_statistics.area_sum
     *
     * @mbggenerated
     */
    public BigDecimal getAreaSum() {
        return areaSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank_statistics.area_sum
     *
     * @param areaSum the value for rank_statistics.area_sum
     *
     * @mbggenerated
     */
    public void setAreaSum(BigDecimal areaSum) {
        this.areaSum = areaSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank_statistics.data_time
     *
     * @return the value of rank_statistics.data_time
     *
     * @mbggenerated
     */
    public Date getDataTime() {
        return dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank_statistics.data_time
     *
     * @param dataTime the value for rank_statistics.data_time
     *
     * @mbggenerated
     */
    public void setDataTime(Date dataTime) {
        this.dataTime = dataTime;
    }

    public String getRegionCode() {
        return regionCode;
    }

    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode;
    }
}