#application port and name
spring:
  application:
    name: JH-Sys
  datasource:
      url: jdbc:postgresql://jiahe-product-db.ch77edmdikxb.rds.cn-northwest-1.amazonaws.com.cn:5432/ground
      username: jiaheinfo
      password: JiaHe2020Cloud
#      url: jdbc:postgresql://192.168.1.223:5433/lianyungang
#      username: postgres
#      password: pgtest2018
      driver-class-name: org.postgresql.Driver
  # druid datasoure
      type: com.alibaba.druid.pool.DruidDataSource
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      enabled: true
      max-file-size: 1024Mb
      max-request-size: 1024Mb

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.jh
  configuration:
    call-setters-on-nulls: true
endpoints:
  shutdown:
    enabled: true
    sensitive: false


server:
  port: 8002

#register server 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

#log
logging:
  file: ../logs/${spring.application.name}.log
  level:
    com.jh: DEBUG
    org:
      springframework:
        boot: info

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000