package com.jh.system.entity;

import java.util.Date;

public class OpLoginLogs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_login_logs.log_id
     *
     * @mbggenerated
     */
    private Integer logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_login_logs.operator
     *
     * @mbggenerated
     */
    private Integer operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_login_logs.operator_name
     *
     * @mbggenerated
     */
    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_login_logs.op_time
     *
     * @mbggenerated
     */
    private Date opTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_login_logs.op_ip
     *
     * @mbggenerated
     */
    private String opIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op_login_logs.op_content
     *
     * @mbggenerated
     */
    private String opContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_login_logs.log_id
     *
     * @return the value of op_login_logs.log_id
     *
     * @mbggenerated
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_login_logs.log_id
     *
     * @param logId the value for op_login_logs.log_id
     *
     * @mbggenerated
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_login_logs.operator
     *
     * @return the value of op_login_logs.operator
     *
     * @mbggenerated
     */
    public Integer getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_login_logs.operator
     *
     * @param operator the value for op_login_logs.operator
     *
     * @mbggenerated
     */
    public void setOperator(Integer operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_login_logs.operator_name
     *
     * @return the value of op_login_logs.operator_name
     *
     * @mbggenerated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_login_logs.operator_name
     *
     * @param operatorName the value for op_login_logs.operator_name
     *
     * @mbggenerated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_login_logs.op_time
     *
     * @return the value of op_login_logs.op_time
     *
     * @mbggenerated
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_login_logs.op_time
     *
     * @param opTime the value for op_login_logs.op_time
     *
     * @mbggenerated
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_login_logs.op_ip
     *
     * @return the value of op_login_logs.op_ip
     *
     * @mbggenerated
     */
    public String getOpIp() {
        return opIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_login_logs.op_ip
     *
     * @param opIp the value for op_login_logs.op_ip
     *
     * @mbggenerated
     */
    public void setOpIp(String opIp) {
        this.opIp = opIp == null ? null : opIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column op_login_logs.op_content
     *
     * @return the value of op_login_logs.op_content
     *
     * @mbggenerated
     */
    public String getOpContent() {
        return opContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column op_login_logs.op_content
     *
     * @param opContent the value for op_login_logs.op_content
     *
     * @mbggenerated
     */
    public void setOpContent(String opContent) {
        this.opContent = opContent == null ? null : opContent.trim();
    }
}