package com.jh.land.mapping;

import com.jh.land.entity.DsAreaRank;
import com.jh.land.entity.RankAreaTimes;
import com.jh.land.model.RankAreaParam;
import com.jh.land.model.RankAreaVO;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface IDsAreaRankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_area_rank
     *
     * @mbggenerated
     */
    int insert(DsAreaRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_area_rank
     *
     * @mbggenerated
     */
    int insertSelective(DsAreaRank record);

    /*
     * 功能描述:查询地块分布表时间轴信息
     * @Param:
     * @Return:
     * @version<1>  2019/12/9  wangli :Created
     */
    List<RankAreaTimes> findRankAreaTimes(RankAreaParam rankAreaParam);

    /*
     * 功能描述:查询所有地块分布表
     * @Param:
     * @Return:
     * @version<1>  2019/12/9  wangli :Created
     */
    List<String> findAllRankAreaTables();

    /*
     * 功能描述: 发布地块分布信息
     * @Param:
     * @Return:
     * @version<1>  2019/12/12  wangli :Created
     */
    int publishData(RankAreaVO rankAreaVO);

}