package com.jh.land.mapping;

import com.jh.land.entity.InitSoilType;

import java.util.List;

public interface InitSoilTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_soil_type
     *
     * @mbggenerated
     */
    int insert(InitSoilType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_soil_type
     *
     * @mbggenerated
     */
    int insertSelective(InitSoilType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_soil_type
     *
     * @mbggenerated
     */
    Integer findSoilTypeByTownCode(String townCode);
}