package com.jh.land.mapping;

import com.jh.land.entity.InitRank;
import com.jh.land.entity.RankStatistics;
import com.jh.land.model.RankAreaTaskVO;
import com.jh.land.model.RankParam;
import com.jh.land.model.RankVO;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Mapper
@Repository
public interface IRankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_rank
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long rankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_rank
     *
     * @mbggenerated
     */
    int insert(InitRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_rank
     *
     * @mbggenerated
     */
    int insertSelective(InitRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_rank
     *
     * @mbggenerated
     */
    InitRank selectByPrimaryKey(Long rankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_rank
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InitRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_rank
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InitRank record);

    /*
     * 功能描述: 查询各镇地块总数量和面积
     * @Param:
     * @Return:
     * @version<1>  2019/10/29  wangli :Created
     */
    List<RankParam> queryRegionRankStatistics(Long parentId);

    /**
     * 根据条件查询地块的数据时间点
     * @param rankParam
     * @return List<String> 数据时间点集合
     * @version <1> 2019/11/6 wangLi:Created.
     */
    List<String> findRankTimes(RankParam rankParam);

    /*
     * 功能描述: 删除重复数据
     * @Param:
     * @Return:
     * @version<1>  2019/12/5  wangli :Created
     */
    int deleteRankInfo(RankAreaTaskVO rankAreaTaskVO);

    /*
     * 功能描述:查询出数据库中所有的地块表
     * @Param:
     * @Return:
     * @version<1>  2019/12/9  wangli :Created
     */
    List<String> findAllRankTables(String tableType);


    /*
     * 功能描述: 查询统计地块信息表
     * @Param:
     * @Return:
     * @version<1>  2019/12/9  wangli :Created
     */
    List<RankStatistics> totalRegionRankStatistics(RankParam rankParam);

    /*
     * 功能描述:查询统计地块时间轴
     * @Param:
     * @Return:
     * @version<1>  2020/1/6  wangli :Created
     */
    List<Map<String,Object>> totalRegionRankTimes(RankParam rankParam);

    /*
     * 功能描述:查询地块年度信息基于区县乡镇级
     * @Param:
     * @Return:
     * @version<1>  2020/1/6  wangli :Created
     */
    List<RankVO> findRankByCounty(RankVO rankVO);

    /*
     * 功能描述:查询最近两年的地块信息
     * @Param:
     * @Return:
     * @version<1>  2020/1/14  wangli :Created
     */
    List<Integer>findTheLatestTwoYearsByRank(RankVO rankVO);

}