#application port and name
spring:
  application:
    name: JH-Land
  datasource:
      url: jdbc:postgresql://192.168.1.248:5432/yangfang
      username: postgres
      password: postgres
#      url: jdbc:postgresql://192.168.1.223:5432/yangfang
#      username: postgres
#      password: pgdev2019

#      url: jdbc:postgresql://192.168.1.223:5433/ground_pro
#      username: postgres
#      password: pgtest2018
      driver-class-name: org.postgresql.Driver
  # druid datasoure
      type: com.alibaba.druid.pool.DruidDataSource
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.jh
  configuration:
    call-setters-on-nulls: true
endpoints:
  shutdown:
    enabled: true
    sensitive: false


server:
  port: 8006

#register server 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

#log
logging:
  file: ../logs/${spring.application.name}.log
  level:
    com.jh: DEBUG
    org:
      springframework:
        boot: info

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000