package com.jh.system.mapping;


import com.jh.system.entity.OpLoginLogs;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface IOpLoginLogsMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_login_logs
     *
     * @mbggenerated
     */
    int insertSelective(OpLoginLogs record);
    /*
     * 功能描述:根据登录id查询登录次数
     * @Param:
     * @Return:
     * @version<1>  2019/11/14  wangli :Created
     */
    int queryLoginNum(Integer accountId);
}