package com.jh.system.mapping;


import com.jh.system.entity.InitRank;
import com.jh.system.model.RankParam;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface IRankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_rank
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long rankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_rank
     *
     * @mbggenerated
     */
    int insert(InitRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_rank
     *
     * @mbggenerated
     */
    int insertSelective(InitRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_rank
     *
     * @mbggenerated
     */
    InitRank selectByPrimaryKey(Long rankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_rank
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InitRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_rank
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InitRank record);

    /*
     * 功能描述: 查询各镇地块总数量和面积
     * @Param:
     * @Return:
     * @version<1>  2019/10/29  wangli :Created
     */
    List<RankParam> queryRegionRankStatistics(Long parentId);

    /**
     * 根据条件查询地块的数据时间点
     * @param RankParam rankParam
     * @return List<String> 数据时间点集合
     * @version <1> 2019/11/6 wangLi:Created.
     */
    List<String> findRankTimes(RankParam rankParam);
}